/**
 * Autogenerated bindings for AetherBid Compact Smart Contract
 * Midnight Network - Preprod Level-3 Compliant
 */

export enum AuctionState {
  Uninitialized = 0,
  BiddingActive = 1,
  RevealActive = 2,
  Finalized = 3
}

export interface ItemMetadata {
  title: string;
  description: string;
  reservePrice: bigint;
}

export interface BidCommitment {
  bidderPk: string;
  commitmentHash: string;
  submittedAt: bigint;
}

export interface BidWitness {
  bidAmount: bigint;
  salt: string;
  bidderSk: string;
}

export interface AetherBidLedgerState {
  auctionState: AuctionState;
  item: ItemMetadata;
  highestBid: bigint;
  highestBidder: string;
  totalBidsCount: bigint;
  biddingEndTime: bigint;
  revealEndTime: bigint;
  sellerPk: string;
  registeredBids: Map<string, BidCommitment>;
}

export const AETHER_BID_CIRCUITS = {
  initializeAuction: 'circuit_initialize_auction_zk',
  submitSealedBid: 'circuit_submit_sealed_bid_zk',
  startRevealPhase: 'circuit_start_reveal_phase_zk',
  revealHighestBid: 'circuit_reveal_highest_bid_zk',
  finalizeAuction: 'circuit_finalize_auction_zk'
} as const;
